-- Prop Intelligence contextual analytics, pgvector analogs, sentiment, and compound alerts.
create extension if not exists vector;

create table if not exists public.player_stretch_embeddings (
  id bigint generated by default as identity primary key,
  sport text not null,
  player_id text not null,
  market text not null,
  stretch_values jsonb not null,
  embedding vector(16) not null,
  next_game_value double precision,
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists player_stretch_embedding_hnsw
  on public.player_stretch_embeddings using hnsw (embedding vector_cosine_ops);
create unique index if not exists player_stretch_natural_key
  on public.player_stretch_embeddings(sport, player_id, market, occurred_at);

create table if not exists public.prop_engagement_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  prop_id text not null,
  action text not null check (action in ('VIEW','SEARCH','CLICK','WATCHLIST','PICK_OVER','PICK_UNDER')),
  created_at timestamptz not null default now()
);
create index if not exists prop_engagement_recent_idx on public.prop_engagement_events(prop_id, created_at desc);

create table if not exists public.compound_prop_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  logic text not null default 'ALL' check (logic in ('ALL','ANY')),
  conditions jsonb not null,
  enabled boolean not null default true,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.alert_deliveries (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid not null references public.compound_prop_alerts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  fingerprint text not null unique, snapshot jsonb not null,
  delivered_at timestamptz not null default now(), read_at timestamptz
);
create index if not exists alert_deliveries_user_idx on public.alert_deliveries(user_id, delivered_at desc);

alter table public.player_stretch_embeddings enable row level security;
alter table public.prop_engagement_events enable row level security;
alter table public.compound_prop_alerts enable row level security;
alter table public.alert_deliveries enable row level security;
drop policy if exists "read historical analogs" on public.player_stretch_embeddings;
drop policy if exists "insert own engagement" on public.prop_engagement_events;
drop policy if exists "manage own alerts" on public.compound_prop_alerts;
drop policy if exists "read own alert deliveries" on public.alert_deliveries;
create policy "read historical analogs" on public.player_stretch_embeddings for select using (true);
create policy "insert own engagement" on public.prop_engagement_events for insert with check (auth.uid() = user_id or user_id is null);
create policy "manage own alerts" on public.compound_prop_alerts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "read own alert deliveries" on public.alert_deliveries for select using (auth.uid() = user_id);

create or replace function public.match_player_stretches(query_embedding vector(16), match_count int default 5)
returns table (id bigint, player_id text, market text, next_game_value double precision, similarity double precision)
language sql stable as $$
  select p.id, p.player_id, p.market, p.next_game_value, 1 - (p.embedding <=> query_embedding) as similarity
  from public.player_stretch_embeddings p order by p.embedding <=> query_embedding limit match_count;
$$;

create or replace function public.match_player_stretches_filtered(
  query_embedding vector(16), query_sport text, query_market text, match_count int default 5
)
returns table (id bigint, player_id text, market text, next_game_value double precision,
               similarity double precision, context jsonb, occurred_at timestamptz)
language sql stable as $$
  select p.id, p.player_id, p.market, p.next_game_value,
         1 - (p.embedding <=> query_embedding) as similarity, p.context, p.occurred_at
  from public.player_stretch_embeddings p
  where p.sport = query_sport and p.market = query_market and p.next_game_value is not null
  order by p.embedding <=> query_embedding limit match_count;
$$;

create table if not exists public.prediction_snapshots (
  id uuid primary key default gen_random_uuid(),
  prop_id text not null, player_id text not null, sport text not null,
  market text not null, side text not null check (side in ('OVER','UNDER')),
  line double precision not null, projection double precision not null,
  hit_probability double precision not null check (hit_probability between 0 and 1),
  model_version text not null, inputs jsonb not null default '{}'::jsonb,
  event_time timestamptz, created_at timestamptz not null default now(),
  actual_value double precision, hit boolean, graded_at timestamptz
);
create index if not exists prediction_calibration_idx
  on public.prediction_snapshots(model_version, sport, market, created_at desc);

create table if not exists public.sports_venues (
  id text primary key, name text not null, latitude double precision not null,
  longitude double precision not null, timezone text not null
);
create table if not exists public.team_schedule (
  id text primary key, sport text not null, team_id text not null,
  opponent_id text, venue_id text references public.sports_venues(id),
  starts_at timestamptz not null, is_home boolean not null,
  status text not null default 'SCHEDULED', raw jsonb not null default '{}'::jsonb
);
create index if not exists team_schedule_lookup_idx
  on public.team_schedule(sport, team_id, starts_at desc);
create table if not exists public.player_fatigue_features (
  player_id text not null, game_id text not null references public.team_schedule(id) on delete cascade,
  rest_days double precision not null, travel_miles double precision not null,
  timezone_change_hours double precision not null, consecutive_games integer not null,
  consecutive_road_games integer not null, recent_minutes jsonb not null default '[]'::jsonb,
  fatigue_score double precision not null, projection_multiplier double precision not null,
  computed_at timestamptz not null default now(), primary key(player_id, game_id)
);
create table if not exists public.officiating_tendency_profiles (
  sport text not null, official_id text not null, official_name text not null,
  sample_size integer not null, raw_rate double precision not null,
  league_rate double precision not null, tendency_index double precision not null,
  confidence double precision not null, metrics jsonb not null default '{}'::jsonb,
  computed_at timestamptz not null default now(), primary key(sport, official_id)
);
alter table public.officiating_tendency_profiles enable row level security;
drop policy if exists "authenticated officiating reads" on public.officiating_tendency_profiles;
create policy "authenticated officiating reads" on public.officiating_tendency_profiles
  for select to authenticated using (true);

create table if not exists public.team_matchup_profiles (
  sport text not null, team_id text not null, team_name text not null,
  season text not null, pick_roll_pressure_proxy double precision not null,
  switch_rate_proxy double precision not null, defender_difficulty double precision not null,
  confidence double precision not null, source text not null,
  metrics jsonb not null default '{}'::jsonb, computed_at timestamptz not null default now(),
  primary key(sport, team_id, season)
);
alter table public.team_matchup_profiles enable row level security;
drop policy if exists "authenticated matchup profile reads" on public.team_matchup_profiles;
create policy "authenticated matchup profile reads" on public.team_matchup_profiles
  for select to authenticated using (true);

alter table public.prediction_snapshots enable row level security;
alter table public.sports_venues enable row level security;
alter table public.team_schedule enable row level security;
alter table public.player_fatigue_features enable row level security;
drop policy if exists "authenticated prediction reads" on public.prediction_snapshots;
drop policy if exists "authenticated venue reads" on public.sports_venues;
drop policy if exists "authenticated schedule reads" on public.team_schedule;
drop policy if exists "authenticated fatigue reads" on public.player_fatigue_features;
create policy "authenticated prediction reads" on public.prediction_snapshots for select to authenticated using (true);
create policy "authenticated venue reads" on public.sports_venues for select to authenticated using (true);
create policy "authenticated schedule reads" on public.team_schedule for select to authenticated using (true);
create policy "authenticated fatigue reads" on public.player_fatigue_features for select to authenticated using (true);
