-- PROP CHAT: authenticated community room with server-derived usernames,
-- blocking, reporting, moderation, and basic anti-spam protection.

begin;

create table if not exists public.prop_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists idx_prop_chat_messages_created_at
on public.prop_chat_messages(created_at desc);

create table if not exists public.prop_chat_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.prop_chat_reports (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.prop_chat_messages(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 200),
  created_at timestamptz not null default now(),
  unique (message_id, reporter_id)
);

create or replace function public.set_prop_chat_username()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  candidate text;
begin
  if new.user_id <> auth.uid() then
    raise exception 'Messages may only be sent as the authenticated user';
  end if;

  select coalesce(
    nullif(trim(p.display_name), ''),
    nullif(trim(u.raw_user_meta_data->>'username'), ''),
    nullif(trim(u.raw_user_meta_data->>'preferred_username'), ''),
    nullif(trim(u.raw_user_meta_data->>'display_name'), ''),
    nullif(trim(u.raw_user_meta_data->>'full_name'), ''),
    nullif(trim(u.raw_user_meta_data->>'name'), '')
  )
  into candidate
  from auth.users u
  left join public.user_profiles p on p.id = u.id
  where u.id = new.user_id;

  candidate := lower(regexp_replace(coalesce(candidate, ''), '[^a-zA-Z0-9_]+', '_', 'g'));
  candidate := trim(both '_' from candidate);
  if char_length(candidate) < 3 then
    candidate := 'user_' || left(replace(new.user_id::text, '-', ''), 8);
  end if;
  new.username := left(candidate, 24);
  new.body := trim(new.body);

  if (
    select count(*)
    from public.prop_chat_messages
    where user_id = new.user_id
      and created_at > now() - interval '10 seconds'
  ) >= 5 then
    raise exception 'Please slow down before sending another message';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_prop_chat_username on public.prop_chat_messages;
create trigger trg_set_prop_chat_username
before insert on public.prop_chat_messages
for each row execute function public.set_prop_chat_username();

alter table public.prop_chat_messages enable row level security;
alter table public.prop_chat_messages force row level security;
alter table public.prop_chat_blocks enable row level security;
alter table public.prop_chat_blocks force row level security;
alter table public.prop_chat_reports enable row level security;
alter table public.prop_chat_reports force row level security;

drop policy if exists prop_chat_messages_read on public.prop_chat_messages;
create policy prop_chat_messages_read on public.prop_chat_messages
for select to authenticated using (true);

drop policy if exists prop_chat_messages_send on public.prop_chat_messages;
create policy prop_chat_messages_send on public.prop_chat_messages
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists prop_chat_messages_delete on public.prop_chat_messages;
create policy prop_chat_messages_delete on public.prop_chat_messages
for delete to authenticated using (
  auth.uid() = user_id
  or coalesce(auth.jwt()->'app_metadata'->>'role', '') in ('owner', 'admin')
);

drop policy if exists prop_chat_blocks_own on public.prop_chat_blocks;
create policy prop_chat_blocks_own on public.prop_chat_blocks
for all to authenticated
using (auth.uid() = blocker_id)
with check (auth.uid() = blocker_id);

drop policy if exists prop_chat_reports_insert on public.prop_chat_reports;
create policy prop_chat_reports_insert on public.prop_chat_reports
for insert to authenticated with check (auth.uid() = reporter_id);

drop policy if exists prop_chat_reports_read on public.prop_chat_reports;
create policy prop_chat_reports_read on public.prop_chat_reports
for select to authenticated using (
  auth.uid() = reporter_id
  or coalesce(auth.jwt()->'app_metadata'->>'role', '') in ('owner', 'admin')
);

do $$
begin
  alter publication supabase_realtime add table public.prop_chat_messages;
exception
  when duplicate_object then null;
end;
$$;

commit;
