-- Supabase SQL setup for user profiles, profile tracking states, and watchlists.
-- Run this in Supabase Dashboard -> SQL Editor.

begin;

-- Keep updated_at fresh on row updates.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 1) User profile table
create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_user_profiles_set_updated_at on public.user_profiles;
create trigger trg_user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.user_profiles force row level security;

drop policy if exists user_profiles_select_own on public.user_profiles;
create policy user_profiles_select_own
on public.user_profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists user_profiles_insert_own on public.user_profiles;
create policy user_profiles_insert_own
on public.user_profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists user_profiles_update_own on public.user_profiles;
create policy user_profiles_update_own
on public.user_profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- 2) User profile tracking state table
create table if not exists public.user_profile_tracking_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  last_auth_event text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_user_profile_tracking_states_set_updated_at on public.user_profile_tracking_states;
create trigger trg_user_profile_tracking_states_set_updated_at
before update on public.user_profile_tracking_states
for each row
execute function public.set_updated_at();

alter table public.user_profile_tracking_states enable row level security;
alter table public.user_profile_tracking_states force row level security;

drop policy if exists tracking_select_own on public.user_profile_tracking_states;
create policy tracking_select_own
on public.user_profile_tracking_states
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists tracking_insert_own on public.user_profile_tracking_states;
create policy tracking_insert_own
on public.user_profile_tracking_states
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists tracking_update_own on public.user_profile_tracking_states;
create policy tracking_update_own
on public.user_profile_tracking_states
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 3) User watchlist table
create table if not exists public.user_watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id text not null,
  player_name text not null,
  sport text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, player_id)
);

create index if not exists idx_user_watchlists_user_id
on public.user_watchlists(user_id);

drop trigger if exists trg_user_watchlists_set_updated_at on public.user_watchlists;
create trigger trg_user_watchlists_set_updated_at
before update on public.user_watchlists
for each row
execute function public.set_updated_at();

alter table public.user_watchlists enable row level security;
alter table public.user_watchlists force row level security;

drop policy if exists watchlists_select_own on public.user_watchlists;
create policy watchlists_select_own
on public.user_watchlists
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists watchlists_insert_own on public.user_watchlists;
create policy watchlists_insert_own
on public.user_watchlists
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists watchlists_update_own on public.user_watchlists;
create policy watchlists_update_own
on public.user_watchlists
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists watchlists_delete_own on public.user_watchlists;
create policy watchlists_delete_own
on public.user_watchlists
for delete
to authenticated
using (auth.uid() = user_id);

commit;
