-- PROP CHAT v6: tiered rooms, game threads, structured prop/slip sharing,
-- expert/creator verification, and provider-neutral push subscriptions.

begin;

alter table public.prop_chat_rooms
  add column if not exists room_type text not null default 'sport'
    check (room_type in ('general', 'sport', 'game')),
  add column if not exists sport text,
  add column if not exists event_id text,
  add column if not exists required_tier text not null default 'edge'
    check (required_tier in ('core', 'edge'));

update public.prop_chat_rooms
set room_type = case when id = 'general' then 'general' else 'sport' end,
    sport = case when id = 'general' then null else upper(id) end,
    required_tier = case when id = 'general' then 'core' else 'edge' end;

create unique index if not exists prop_chat_rooms_event_id_unique
  on public.prop_chat_rooms(event_id) where event_id is not null;

alter table public.user_profiles
  add column if not exists chat_role text not null default 'member'
    check (chat_role in ('member', 'expert', 'creator')),
  add column if not exists chat_verified boolean not null default false;
revoke update (chat_role, chat_verified) on public.user_profiles from authenticated;

alter table public.prop_chat_messages
  drop constraint if exists prop_chat_messages_attachment_kind_check;
alter table public.prop_chat_messages
  add constraint prop_chat_messages_attachment_kind_check
  check (attachment_kind in ('image', 'ticket', 'prop', 'slip')),
  add column if not exists shared_payload jsonb;

alter table public.prop_chat_direct_messages
  drop constraint if exists prop_chat_direct_messages_attachment_kind_check;
alter table public.prop_chat_direct_messages
  add constraint prop_chat_direct_messages_attachment_kind_check
  check (attachment_kind in ('image', 'ticket', 'prop', 'slip')),
  add column if not exists shared_payload jsonb;

create or replace function public.prop_chat_access_level()
returns integer language sql stable security definer set search_path = public, auth as $$
  select case
    when coalesce((select raw_app_meta_data->>'role' from auth.users where id = auth.uid()), '') in ('owner','admin') then 2
    when coalesce((select subscription_tier from public.user_profiles where id = auth.uid()), 'free') = 'edge' then 2
    when coalesce((select subscription_tier from public.user_profiles where id = auth.uid()), 'free') = 'core' then 1
    else 0
  end;
$$;

create or replace function public.can_access_prop_chat_room(target text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.prop_chat_rooms r
    where r.id = target and r.is_active
      and public.prop_chat_access_level() >=
        case when r.required_tier = 'edge' then 2 else 1 end
  );
$$;

create or replace function public.create_prop_chat_game_thread(
  game_event_id text, game_sport text, game_name text
) returns text language plpgsql security definer set search_path = public as $$
declare room_key text;
begin
  if public.prop_chat_access_level() < 2 then
    raise exception 'Pro access is required for game threads';
  end if;
  if length(trim(game_event_id)) not between 2 and 120
     or length(trim(game_name)) not between 3 and 80 then
    raise exception 'A valid event and game name are required';
  end if;
  room_key := 'game_' || left(md5(trim(game_event_id)), 20);
  insert into public.prop_chat_rooms(id, name, position, is_active, room_type, sport, event_id, required_tier)
  values (
    room_key, left(trim(game_name), 80),
    1000 + (abs(hashtext(trim(game_event_id))) % 100000), true,
    'game', left(upper(trim(game_sport)), 16), left(trim(game_event_id), 120), 'edge'
  )
  on conflict (event_id) where event_id is not null do update
    set name = excluded.name, sport = excluded.sport, is_active = true
  returning id into room_key;
  return room_key;
end;
$$;

create or replace function public.set_prop_chat_member_role(
  target_user uuid, new_role text, verified boolean
) returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_prop_chat_moderator() then raise exception 'Moderator access required'; end if;
  if new_role not in ('member','expert','creator') then raise exception 'Invalid chat role'; end if;
  update public.user_profiles set chat_role = new_role, chat_verified = verified
  where id = target_user;
end;
$$;

create table if not exists public.prop_chat_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_key text not null,
  platform text not null check (platform in ('web','android','ios','windows','macos','linux')),
  endpoint text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, device_key)
);
alter table public.prop_chat_push_subscriptions enable row level security;
alter table public.prop_chat_push_subscriptions force row level security;
create policy prop_chat_push_own on public.prop_chat_push_subscriptions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists prop_chat_rooms_read on public.prop_chat_rooms;
create policy prop_chat_rooms_read on public.prop_chat_rooms
  for select to authenticated using (
    public.can_access_prop_chat_room(id) or public.is_prop_chat_moderator()
  );
drop policy if exists prop_chat_messages_read on public.prop_chat_messages;
create policy prop_chat_messages_read on public.prop_chat_messages
  for select to authenticated using (
    public.can_access_prop_chat_room(room_id)
    and (deleted_at is null or public.is_prop_chat_moderator())
  );
drop policy if exists prop_chat_messages_send on public.prop_chat_messages;
create policy prop_chat_messages_send on public.prop_chat_messages
  for insert to authenticated with check (
    auth.uid() = user_id and public.can_access_prop_chat_room(room_id)
  );

drop policy if exists prop_chat_conversations_read on public.prop_chat_conversations;
create policy prop_chat_conversations_read on public.prop_chat_conversations
  for select to authenticated using (
    public.prop_chat_access_level() >= 1
    and public.is_prop_chat_conversation_member(id)
  );
drop policy if exists prop_chat_conversation_members_read on public.prop_chat_conversation_members;
create policy prop_chat_conversation_members_read on public.prop_chat_conversation_members
  for select to authenticated using (
    public.prop_chat_access_level() >= 1
    and public.is_prop_chat_conversation_member(conversation_id)
  );
drop policy if exists prop_chat_direct_messages_read on public.prop_chat_direct_messages;
create policy prop_chat_direct_messages_read on public.prop_chat_direct_messages
  for select to authenticated using (
    public.prop_chat_access_level() >= 1
    and public.is_prop_chat_conversation_member(conversation_id)
  );
drop policy if exists prop_chat_direct_messages_send on public.prop_chat_direct_messages;
create policy prop_chat_direct_messages_send on public.prop_chat_direct_messages
  for insert to authenticated with check (
    public.prop_chat_access_level() >= 1
    and user_id = auth.uid()
    and public.is_prop_chat_conversation_member(conversation_id)
  );

create or replace function public.enforce_prop_chat_message_v4()
returns trigger language plpgsql security definer set search_path = public, auth as $$
declare candidate text; app_role text; profile_role text; profile_verified boolean;
  active_restriction text; blocked_term text;
begin
  if new.user_id <> auth.uid() or not public.can_access_prop_chat_room(new.room_id) then
    raise exception 'Room access denied';
  end if;
  select restriction into active_restriction from public.prop_chat_restrictions
  where user_id = new.user_id and restriction in ('muted','suspended','banned')
    and (expires_at is null or expires_at > now());
  if active_restriction is not null then raise exception 'Chat access is currently restricted'; end if;
  select coalesce(nullif(trim(p.username), ''), 'user_' || left(replace(new.user_id::text, '-', ''), 8)),
    coalesce(u.raw_app_meta_data->>'role','user'), coalesce(p.chat_role,'member'), coalesce(p.chat_verified,false)
  into candidate, app_role, profile_role, profile_verified
  from auth.users u left join public.user_profiles p on p.id=u.id where u.id=new.user_id;
  new.username := left(candidate,24);
  new.author_role := case when app_role in ('owner','admin') then app_role
    when profile_verified and profile_role in ('expert','creator') then profile_role else 'user' end;
  new.body := trim(new.body);
  new.link_url := public.validate_prop_chat_link(new.link_url);
  if new.attachment_kind in ('prop','slip') then
    if public.prop_chat_access_level() < 2 or new.shared_payload is null
       or jsonb_typeof(new.shared_payload) <> 'object'
       or octet_length(new.shared_payload::text) > 20000 then
      raise exception 'Valid Pro shared analysis is required';
    end if;
  elsif new.shared_payload is not null then raise exception 'Unexpected shared payload';
  end if;
  if new.attachment_path is not null and
     new.attachment_path !~ ('^' || new.user_id::text || '/[a-f0-9-]{36}\.(jpg|jpeg|png|webp)$') then
    raise exception 'Invalid attachment path';
  end if;
  select term into blocked_term from public.prop_chat_blocked_terms
    where position(lower(term) in lower(new.body)) > 0 limit 1;
  if blocked_term is not null then raise exception 'Message blocked by community safety filter'; end if;
  if tg_op='INSERT' and (select count(*) from public.prop_chat_messages
    where user_id=new.user_id and created_at > now()-interval '60 seconds') >= 12 then
    raise exception 'Message limit reached. Please wait a moment';
  end if;
  if tg_op='UPDATE' then new.edited_at:=now(); end if;
  return new;
end;
$$;
drop trigger if exists trg_enforce_prop_chat_message_v4 on public.prop_chat_messages;
create trigger trg_enforce_prop_chat_message_v4
before insert or update of body, link_url, attachment_path, attachment_kind, shared_payload
on public.prop_chat_messages for each row execute function public.enforce_prop_chat_message_v4();

commit;
