-- PROP CHAT v3: operational completion for unread monitoring, moderation
-- notices, configurable filtering, automatic retention, and health alerts.

begin;

create table if not exists public.prop_chat_blocked_terms (
  term text primary key,
  category text not null default 'safety',
  created_at timestamptz not null default now()
);

insert into public.prop_chat_blocked_terms(term, category) values
  ('free money', 'scam'),
  ('guaranteed lock', 'scam'),
  ('wire transfer', 'scam'),
  ('send cash', 'scam'),
  ('dm me', 'spam')
on conflict (term) do nothing;

create table if not exists public.prop_chat_moderation_notices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  restriction text not null,
  reason text not null,
  expires_at timestamptz,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.prop_chat_operational_alerts (
  id bigint generated by default as identity primary key,
  severity text not null check (severity in ('warning', 'critical')),
  alert_type text not null,
  details jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.prop_chat_maintenance (
  task text primary key,
  last_run_at timestamptz not null default 'epoch'
);

alter table public.prop_chat_blocked_terms enable row level security;
alter table public.prop_chat_moderation_notices enable row level security;
alter table public.prop_chat_operational_alerts enable row level security;
alter table public.prop_chat_maintenance enable row level security;

create policy prop_chat_blocked_terms_moderator on public.prop_chat_blocked_terms
for all to authenticated using (public.is_prop_chat_moderator())
with check (public.is_prop_chat_moderator());
create policy prop_chat_notices_own on public.prop_chat_moderation_notices
for select to authenticated using (auth.uid() = user_id or public.is_prop_chat_moderator());
create policy prop_chat_notices_ack on public.prop_chat_moderation_notices
for update to authenticated using (auth.uid() = user_id)
with check (auth.uid() = user_id);
create policy prop_chat_alerts_moderator on public.prop_chat_operational_alerts
for all to authenticated using (public.is_prop_chat_moderator())
with check (public.is_prop_chat_moderator());

create or replace function public.enforce_prop_chat_message_v2()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  candidate text;
  role_value text;
  active_restriction text;
  blocked_term text;
begin
  if tg_op = 'INSERT' and new.user_id <> auth.uid() then
    raise exception 'Messages may only be sent as the authenticated user';
  end if;
  if tg_op = 'UPDATE' and old.user_id <> auth.uid() and not public.is_prop_chat_moderator() then
    raise exception 'Message update not allowed';
  end if;

  select restriction into active_restriction
  from public.prop_chat_restrictions
  where user_id = new.user_id
    and restriction in ('muted', 'suspended', 'banned')
    and (expires_at is null or expires_at > now());
  if active_restriction is not null then
    raise exception 'Chat access is currently restricted';
  end if;

  select coalesce(nullif(trim(p.username), ''), 'user_' || left(replace(new.user_id::text, '-', ''), 8)),
         coalesce(u.raw_app_meta_data->>'role', 'user')
  into candidate, role_value
  from auth.users u
  left join public.user_profiles p on p.id = u.id
  where u.id = new.user_id;

  new.username := left(candidate, 24);
  new.author_role := case when role_value in ('owner', 'admin') then role_value else 'user' end;
  new.body := trim(new.body);

  if new.body ~* '(https?://|www\.|[a-z0-9-]+\.(com|net|org|io)(/|\s|$))' then
    raise exception 'Links are not allowed in PROP CHAT';
  end if;
  select term into blocked_term
  from public.prop_chat_blocked_terms
  where position(lower(term) in lower(new.body)) > 0
  limit 1;
  if blocked_term is not null then
    raise exception 'Message blocked by community safety filter';
  end if;
  if tg_op = 'INSERT' and (
    select count(*) from public.prop_chat_messages
    where user_id = new.user_id and created_at > now() - interval '60 seconds'
  ) >= 12 then
    raise exception 'Message limit reached. Please wait a moment';
  end if;
  if tg_op = 'UPDATE' then new.edited_at := now(); end if;
  return new;
end;
$$;

create or replace function public.notify_prop_chat_restriction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.prop_chat_moderation_notices(user_id, restriction, reason, expires_at)
  values (new.user_id, new.restriction, new.reason, new.expires_at);
  return new;
end;
$$;

drop trigger if exists trg_notify_prop_chat_restriction on public.prop_chat_restrictions;
create trigger trg_notify_prop_chat_restriction
after insert or update of restriction, reason, expires_at on public.prop_chat_restrictions
for each row execute function public.notify_prop_chat_restriction();

create or replace function public.alert_on_prop_chat_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare open_count integer;
begin
  select count(*) into open_count from public.prop_chat_reports where status = 'open';
  if open_count >= 5 and not exists (
    select 1 from public.prop_chat_operational_alerts
    where alert_type = 'open_reports'
      and resolved_at is null
      and created_at > now() - interval '1 hour'
  ) then
    insert into public.prop_chat_operational_alerts(severity, alert_type, details)
    values ('warning', 'open_reports', jsonb_build_object('count', open_count));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_alert_on_prop_chat_report on public.prop_chat_reports;
create trigger trg_alert_on_prop_chat_report
after insert on public.prop_chat_reports
for each statement execute function public.alert_on_prop_chat_report();

create or replace function public.maintain_prop_chat_retention()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare last_run timestamptz;
begin
  select last_run_at into last_run from public.prop_chat_maintenance
  where task = 'retention' for update;
  if last_run is null then
    insert into public.prop_chat_maintenance(task, last_run_at)
    values ('retention', now()) on conflict (task) do nothing;
  elsif last_run < now() - interval '24 hours' then
    update public.prop_chat_maintenance set last_run_at = now() where task = 'retention';
    delete from public.prop_chat_messages where created_at < now() - interval '90 days';
    delete from public.prop_chat_presence where last_seen_at < now() - interval '1 day';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_maintain_prop_chat_retention on public.prop_chat_messages;
create trigger trg_maintain_prop_chat_retention
after insert on public.prop_chat_messages
for each statement execute function public.maintain_prop_chat_retention();

create or replace function public.prop_chat_unread_summary()
returns table(room_id text, unread_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select r.id,
    count(m.id) filter (
      where m.user_id <> auth.uid()
        and m.created_at > coalesce(s.last_read_at, 'epoch'::timestamptz)
        and m.deleted_at is null
    )
  from public.prop_chat_rooms r
  left join public.prop_chat_read_state s
    on s.room_id = r.id and s.user_id = auth.uid()
  left join public.prop_chat_messages m on m.room_id = r.id
  where r.is_active
  group by r.id, s.last_read_at;
$$;

create or replace function public.acknowledge_prop_chat_notice(notice_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.prop_chat_moderation_notices
  set acknowledged_at = now()
  where id = notice_id and user_id = auth.uid();
$$;

do $$
begin
  alter publication supabase_realtime add table public.prop_chat_moderation_notices;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.prop_chat_operational_alerts;
exception when duplicate_object then null;
end $$;

commit;
