-- PROP CHAT v4: private direct messages, private image attachments, and
-- server-validated links. Attachments are stored in a private bucket and
-- exposed only through short-lived signed URLs.

begin;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'prop-chat-private',
  'prop-chat-private',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

create table if not exists public.prop_chat_conversations (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prop_chat_conversation_members (
  conversation_id uuid not null references public.prop_chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.prop_chat_direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.prop_chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  body text not null default '' check (char_length(body) <= 500),
  attachment_path text,
  attachment_kind text check (attachment_kind in ('image', 'ticket')),
  link_url text,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  check (
    char_length(trim(body)) > 0
    or attachment_path is not null
  )
);

create table if not exists public.prop_chat_direct_reports (
  id bigint generated by default as identity primary key,
  message_id bigint references public.prop_chat_direct_messages(id) on delete set null,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  message_user_id uuid,
  message_username text,
  message_body text,
  attachment_path text,
  reason text not null check (char_length(reason) between 3 and 200),
  status text not null default 'open'
    check (status in ('open', 'reviewed', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique(message_id, reporter_id)
);

alter table public.prop_chat_messages
  add column if not exists attachment_path text,
  add column if not exists attachment_kind text
    check (attachment_kind in ('image', 'ticket')),
  add column if not exists link_url text;

alter table public.prop_chat_conversations enable row level security;
alter table public.prop_chat_conversations force row level security;
alter table public.prop_chat_conversation_members enable row level security;
alter table public.prop_chat_conversation_members force row level security;
alter table public.prop_chat_direct_messages enable row level security;
alter table public.prop_chat_direct_messages force row level security;
alter table public.prop_chat_direct_reports enable row level security;
alter table public.prop_chat_direct_reports force row level security;

create or replace function public.is_prop_chat_conversation_member(target uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.prop_chat_conversation_members
    where conversation_id = target and user_id = auth.uid()
  );
$$;

create or replace function public.start_prop_chat_direct_conversation(other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  conversation uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if other_user is null or other_user = auth.uid() then
    raise exception 'Choose another member';
  end if;
  if exists (
    select 1 from public.prop_chat_blocks
    where (blocker_id = auth.uid() and blocked_id = other_user)
       or (blocker_id = other_user and blocked_id = auth.uid())
  ) then raise exception 'Direct messaging is unavailable for this member'; end if;

  select c.id into conversation
  from public.prop_chat_conversations c
  join public.prop_chat_conversation_members mine
    on mine.conversation_id = c.id and mine.user_id = auth.uid()
  join public.prop_chat_conversation_members theirs
    on theirs.conversation_id = c.id and theirs.user_id = other_user
  where (select count(*) from public.prop_chat_conversation_members x
         where x.conversation_id = c.id) = 2
  limit 1;

  if conversation is null then
    insert into public.prop_chat_conversations(created_by)
    values (auth.uid()) returning id into conversation;
    insert into public.prop_chat_conversation_members(conversation_id, user_id)
    values (conversation, auth.uid()), (conversation, other_user);
  end if;
  return conversation;
end;
$$;

create or replace function public.find_prop_chat_members(query text)
returns table(user_id uuid, username text)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.username
  from public.user_profiles p
  where auth.uid() is not null
    and p.id <> auth.uid()
    and p.username is not null
    and p.username ilike replace(replace(trim(query), '%', '\%'), '_', '\_') || '%'
    and not exists (
      select 1 from public.prop_chat_blocks b
      where (b.blocker_id = auth.uid() and b.blocked_id = p.id)
         or (b.blocker_id = p.id and b.blocked_id = auth.uid())
    )
  order by p.username
  limit 10;
$$;

create or replace function public.prop_chat_direct_conversations()
returns table(
  conversation_id uuid,
  other_user_id uuid,
  other_username text,
  updated_at timestamptz,
  unread_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select c.id, other.user_id,
    coalesce(p.username, 'member'), c.updated_at,
    count(dm.id) filter (
      where dm.user_id <> auth.uid()
        and dm.created_at > mine.last_read_at
        and dm.deleted_at is null
    )
  from public.prop_chat_conversations c
  join public.prop_chat_conversation_members mine
    on mine.conversation_id = c.id and mine.user_id = auth.uid()
  join public.prop_chat_conversation_members other
    on other.conversation_id = c.id and other.user_id <> auth.uid()
  left join public.user_profiles p on p.id = other.user_id
  left join public.prop_chat_direct_messages dm on dm.conversation_id = c.id
  group by c.id, other.user_id, p.username, c.updated_at, mine.last_read_at
  order by c.updated_at desc;
$$;

create or replace function public.validate_prop_chat_link(candidate text)
returns text
language plpgsql
immutable
as $$
declare normalized text;
begin
  if candidate is null or trim(candidate) = '' then return null; end if;
  normalized := trim(candidate);
  if normalized !~* '^https://[a-z0-9.-]+(?::[0-9]+)?(?:/[^[:space:]]*)?$' then
    raise exception 'Only secure HTTPS links are allowed';
  end if;
  if normalized ~* '^https://(?:localhost|127\.0\.0\.1|0\.0\.0\.0|\[?::1\]?)(?::|/|$)'
     or normalized ~* '^https://(?:10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)' then
    raise exception 'Private network links are not allowed';
  end if;
  return left(normalized, 1000);
end;
$$;

create or replace function public.enforce_prop_chat_message_v4()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  candidate text;
  role_value text;
  active_restriction text;
  blocked_term text;
begin
  if new.user_id <> auth.uid() then
    raise exception 'Messages may only be sent as the authenticated user';
  end if;
  select restriction into active_restriction
  from public.prop_chat_restrictions
  where user_id = new.user_id
    and restriction in ('muted', 'suspended', 'banned')
    and (expires_at is null or expires_at > now());
  if active_restriction is not null then
    raise exception 'Chat access is currently restricted';
  end if;
  select coalesce(nullif(trim(p.username), ''),
           'user_' || left(replace(new.user_id::text, '-', ''), 8)),
         coalesce(u.raw_app_meta_data->>'role', 'user')
    into candidate, role_value
  from auth.users u left join public.user_profiles p on p.id = u.id
  where u.id = new.user_id;
  new.username := left(candidate, 24);
  new.author_role := case when role_value in ('owner', 'admin')
    then role_value else 'user' end;
  new.body := trim(new.body);
  new.link_url := public.validate_prop_chat_link(new.link_url);
  if new.attachment_path is not null and
     new.attachment_path !~ ('^' || new.user_id::text || '/[a-f0-9-]{36}\.(jpg|jpeg|png|webp)$') then
    raise exception 'Invalid attachment path';
  end if;
  select term into blocked_term from public.prop_chat_blocked_terms
  where position(lower(term) in lower(new.body)) > 0 limit 1;
  if blocked_term is not null then
    raise exception 'Message blocked by community safety filter';
  end if;
  if (select count(*) from public.prop_chat_messages
      where user_id = new.user_id and created_at > now() - interval '60 seconds') >= 12 then
    raise exception 'Message limit reached. Please wait a moment';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_prop_chat_message_v2 on public.prop_chat_messages;
drop trigger if exists trg_enforce_prop_chat_message_v4 on public.prop_chat_messages;
create trigger trg_enforce_prop_chat_message_v4
before insert on public.prop_chat_messages
for each row execute function public.enforce_prop_chat_message_v4();

create or replace function public.enforce_prop_chat_direct_message()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare candidate text; blocked_term text;
begin
  if new.user_id <> auth.uid()
     or not public.is_prop_chat_conversation_member(new.conversation_id) then
    raise exception 'Conversation access denied';
  end if;
  if exists (
    select 1 from public.prop_chat_conversation_members a
    join public.prop_chat_conversation_members b
      on b.conversation_id = a.conversation_id and b.user_id <> a.user_id
    join public.prop_chat_blocks x
      on (x.blocker_id = a.user_id and x.blocked_id = b.user_id)
      or (x.blocker_id = b.user_id and x.blocked_id = a.user_id)
    where a.conversation_id = new.conversation_id and a.user_id = auth.uid()
  ) then raise exception 'Direct messaging is unavailable for this member'; end if;
  select coalesce(nullif(trim(username), ''),
    'user_' || left(replace(new.user_id::text, '-', ''), 8))
  into candidate from public.user_profiles where id = new.user_id;
  new.username := left(coalesce(candidate,
    'user_' || left(replace(new.user_id::text, '-', ''), 8)), 24);
  new.body := trim(new.body);
  new.link_url := public.validate_prop_chat_link(new.link_url);
  if new.attachment_path is not null and
     new.attachment_path !~ ('^' || new.user_id::text || '/[a-f0-9-]{36}\.(jpg|jpeg|png|webp)$') then
    raise exception 'Invalid attachment path';
  end if;
  select term into blocked_term from public.prop_chat_blocked_terms
  where position(lower(term) in lower(new.body)) > 0 limit 1;
  if blocked_term is not null then raise exception 'Message blocked by safety filter'; end if;
  if (select count(*) from public.prop_chat_direct_messages
      where user_id = new.user_id and created_at > now() - interval '60 seconds') >= 20 then
    raise exception 'Message limit reached. Please wait a moment';
  end if;
  update public.prop_chat_conversations set updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$;

create trigger trg_enforce_prop_chat_direct_message
before insert on public.prop_chat_direct_messages
for each row execute function public.enforce_prop_chat_direct_message();

create or replace function public.capture_prop_chat_direct_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.prop_chat_direct_messages d
    where d.id = new.message_id
      and public.is_prop_chat_conversation_member(d.conversation_id)
  ) then raise exception 'Message access denied'; end if;
  select user_id, username, body, attachment_path
  into new.message_user_id, new.message_username, new.message_body, new.attachment_path
  from public.prop_chat_direct_messages where id = new.message_id;
  return new;
end;
$$;

create trigger trg_capture_prop_chat_direct_report
before insert on public.prop_chat_direct_reports
for each row execute function public.capture_prop_chat_direct_report();

create policy prop_chat_conversations_read on public.prop_chat_conversations
for select to authenticated using (public.is_prop_chat_conversation_member(id));
create policy prop_chat_conversation_members_read on public.prop_chat_conversation_members
for select to authenticated using (public.is_prop_chat_conversation_member(conversation_id));
create policy prop_chat_conversation_members_update on public.prop_chat_conversation_members
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy prop_chat_direct_messages_read on public.prop_chat_direct_messages
for select to authenticated using (public.is_prop_chat_conversation_member(conversation_id));
create policy prop_chat_direct_messages_send on public.prop_chat_direct_messages
for insert to authenticated with check (
  user_id = auth.uid() and public.is_prop_chat_conversation_member(conversation_id)
);
create policy prop_chat_direct_messages_edit on public.prop_chat_direct_messages
for update to authenticated using (
  user_id = auth.uid() and created_at > now() - interval '5 minutes'
) with check (user_id = auth.uid());
create policy prop_chat_direct_reports_insert on public.prop_chat_direct_reports
for insert to authenticated with check (reporter_id = auth.uid());
create policy prop_chat_direct_reports_read on public.prop_chat_direct_reports
for select to authenticated using (
  reporter_id = auth.uid() or public.is_prop_chat_moderator()
);
create policy prop_chat_direct_reports_moderate on public.prop_chat_direct_reports
for update to authenticated using (public.is_prop_chat_moderator())
with check (public.is_prop_chat_moderator());

create policy prop_chat_storage_insert on storage.objects
for insert to authenticated with check (
  bucket_id = 'prop-chat-private'
  and (storage.foldername(name))[1] = auth.uid()::text
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);
create policy prop_chat_storage_read_own on storage.objects
for select to authenticated using (
  bucket_id = 'prop-chat-private'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or exists (
      select 1 from public.prop_chat_messages m
      where m.attachment_path = name and m.deleted_at is null
    )
    or exists (
      select 1 from public.prop_chat_direct_messages d
      where d.attachment_path = name
        and d.deleted_at is null
        and public.is_prop_chat_conversation_member(d.conversation_id)
    )
  )
);
create policy prop_chat_storage_delete_own on storage.objects
for delete to authenticated using (
  bucket_id = 'prop-chat-private'
  and (storage.foldername(name))[1] = auth.uid()::text
);

do $$
begin
  alter publication supabase_realtime add table public.prop_chat_direct_messages;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.prop_chat_conversations;
exception when duplicate_object then null;
end $$;

commit;
